[project]
name = "odoo-addons-oca-product-variant"
version = "19.0.20260908.1"
dependencies = [
    "odoo-addon-product_variant_attribute_tax==19.0.*",
    "odoo-addon-product_variant_configurator==19.0.*",
    "odoo-addon-product_variant_default_code==19.0.*",
    "odoo-addon-product_variant_name==19.0.*",
    "odoo-addon-product_variant_sale_price==19.0.*",
    "odoo-addon-product_variant_specific_description==19.0.*",
    "odoo-addon-purchase_variant_configurator==19.0.*",
    "odoo-addon-sale_variant_configurator==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
